namespace Advanced_Combat_Tracker
{
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    internal class Options_ColorGraphing : UserControl
    {
        private Button btnResetEncBarColors;
        private Button btnResetGraphFillColors;
        internal ColorControl ccEncBarAvgText;
        internal ColorControl ccEncBarBackFill;
        internal ColorControl ccEncBarColor1;
        internal ColorControl ccEncBarColor2;
        internal ColorControl ccEncBarColor3;
        internal ColorControl ccEncBarLegendText;
        internal ColorControl ccEncBarOutlining;
        internal ColorControl ccEncBarText;
        internal ColorControl ccEncBarYLines;
        internal ColorControl ccGraphFill1;
        internal ColorControl ccGraphFill10;
        internal ColorControl ccGraphFill11;
        internal ColorControl ccGraphFill12;
        internal ColorControl ccGraphFill13;
        internal ColorControl ccGraphFill14;
        internal ColorControl ccGraphFill15;
        internal ColorControl ccGraphFill16;
        internal ColorControl ccGraphFill17;
        internal ColorControl ccGraphFill18;
        internal ColorControl ccGraphFill19;
        internal ColorControl ccGraphFill2;
        internal ColorControl ccGraphFill20;
        internal ColorControl ccGraphFill21;
        internal ColorControl ccGraphFill22;
        internal ColorControl ccGraphFill23;
        internal ColorControl ccGraphFill24;
        internal ColorControl ccGraphFill25;
        internal ColorControl ccGraphFill26;
        internal ColorControl ccGraphFill27;
        internal ColorControl ccGraphFill28;
        internal ColorControl ccGraphFill3;
        internal ColorControl ccGraphFill4;
        internal ColorControl ccGraphFill5;
        internal ColorControl ccGraphFill6;
        internal ColorControl ccGraphFill7;
        internal ColorControl ccGraphFill8;
        internal ColorControl ccGraphFill9;
        private IContainer components;
        private FlowLayoutPanel flowLayoutPanel1;
        private FlowLayoutPanel flowLayoutPanel2;
        private GroupBox groupBox1;
        private GroupBox groupBox2;

        public Options_ColorGraphing()
        {
            this.InitializeComponent();
        }

        private void btnResetEncBarColors_Click(object sender, EventArgs e)
        {
            MessageBox.Show("You must restart ACT to revert these color changes.", "Restart required", MessageBoxButtons.OK, MessageBoxIcon.Asterisk);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccEncBarAvgText.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccEncBarBackFill.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccEncBarColor1.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccEncBarColor2.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccEncBarColor3.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccEncBarLegendText.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccEncBarOutlining.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccEncBarText.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccEncBarYLines.Name);
        }

        private void btnResetGraphFillColors_Click(object sender, EventArgs e)
        {
            MessageBox.Show("You must restart ACT to revert these color changes.", "Restart required", MessageBoxButtons.OK, MessageBoxIcon.Asterisk);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill1.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill2.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill3.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill4.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill5.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill6.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill7.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill8.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill9.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill10.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill11.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill12.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill13.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill14.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill15.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill16.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill17.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill18.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill19.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill20.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill21.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill22.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill23.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill24.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill25.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill26.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill27.Name);
            ActGlobals.oFormActMain.xmlSettings.RemoveControlSetting(this.ccGraphFill28.Name);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.flowLayoutPanel1 = new FlowLayoutPanel();
            this.ccEncBarBackFill = new ColorControl();
            this.ccEncBarLegendText = new ColorControl();
            this.ccEncBarYLines = new ColorControl();
            this.ccEncBarOutlining = new ColorControl();
            this.ccEncBarAvgText = new ColorControl();
            this.ccEncBarColor1 = new ColorControl();
            this.ccEncBarColor2 = new ColorControl();
            this.ccEncBarColor3 = new ColorControl();
            this.ccEncBarText = new ColorControl();
            this.groupBox1 = new GroupBox();
            this.btnResetEncBarColors = new Button();
            this.groupBox2 = new GroupBox();
            this.btnResetGraphFillColors = new Button();
            this.flowLayoutPanel2 = new FlowLayoutPanel();
            this.ccGraphFill1 = new ColorControl();
            this.ccGraphFill2 = new ColorControl();
            this.ccGraphFill3 = new ColorControl();
            this.ccGraphFill4 = new ColorControl();
            this.ccGraphFill5 = new ColorControl();
            this.ccGraphFill6 = new ColorControl();
            this.ccGraphFill7 = new ColorControl();
            this.ccGraphFill8 = new ColorControl();
            this.ccGraphFill9 = new ColorControl();
            this.ccGraphFill10 = new ColorControl();
            this.ccGraphFill11 = new ColorControl();
            this.ccGraphFill12 = new ColorControl();
            this.ccGraphFill13 = new ColorControl();
            this.ccGraphFill14 = new ColorControl();
            this.ccGraphFill15 = new ColorControl();
            this.ccGraphFill16 = new ColorControl();
            this.ccGraphFill17 = new ColorControl();
            this.ccGraphFill18 = new ColorControl();
            this.ccGraphFill19 = new ColorControl();
            this.ccGraphFill20 = new ColorControl();
            this.ccGraphFill21 = new ColorControl();
            this.ccGraphFill22 = new ColorControl();
            this.ccGraphFill23 = new ColorControl();
            this.ccGraphFill24 = new ColorControl();
            this.ccGraphFill25 = new ColorControl();
            this.ccGraphFill26 = new ColorControl();
            this.ccGraphFill27 = new ColorControl();
            this.ccGraphFill28 = new ColorControl();
            this.flowLayoutPanel1.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.flowLayoutPanel2.SuspendLayout();
            base.SuspendLayout();
            this.flowLayoutPanel1.Controls.Add(this.ccEncBarBackFill);
            this.flowLayoutPanel1.Controls.Add(this.ccEncBarLegendText);
            this.flowLayoutPanel1.Controls.Add(this.ccEncBarYLines);
            this.flowLayoutPanel1.Controls.Add(this.ccEncBarOutlining);
            this.flowLayoutPanel1.Controls.Add(this.ccEncBarAvgText);
            this.flowLayoutPanel1.Controls.Add(this.ccEncBarColor1);
            this.flowLayoutPanel1.Controls.Add(this.ccEncBarColor2);
            this.flowLayoutPanel1.Controls.Add(this.ccEncBarColor3);
            this.flowLayoutPanel1.Controls.Add(this.ccEncBarText);
            this.flowLayoutPanel1.Dock = DockStyle.Fill;
            this.flowLayoutPanel1.FlowDirection = FlowDirection.TopDown;
            this.flowLayoutPanel1.Location = new Point(3, 0x10);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new Size(0xee, 0x146);
            this.flowLayoutPanel1.TabIndex = 1;
            this.ccEncBarBackFill.AutoSize = true;
            this.ccEncBarBackFill.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccEncBarBackFill.ForeColorSetting = SystemColors.ControlLight;
            this.ccEncBarBackFill.Location = new Point(3, 3);
            this.ccEncBarBackFill.Name = "ccEncBarBackFill";
            this.ccEncBarBackFill.Size = new Size(0x90, 30);
            this.ccEncBarBackFill.TabIndex = 0;
            this.ccEncBarBackFill.Text = "Graph background fill";
            this.ccEncBarLegendText.AutoSize = true;
            this.ccEncBarLegendText.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccEncBarLegendText.ForeColorSetting = SystemColors.ControlText;
            this.ccEncBarLegendText.Location = new Point(3, 0x27);
            this.ccEncBarLegendText.Name = "ccEncBarLegendText";
            this.ccEncBarLegendText.Size = new Size(0x75, 30);
            this.ccEncBarLegendText.TabIndex = 0;
            this.ccEncBarLegendText.Text = "Axis legend text";
            this.ccEncBarYLines.AutoSize = true;
            this.ccEncBarYLines.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccEncBarYLines.ForeColorSetting = SystemColors.ControlDark;
            this.ccEncBarYLines.Location = new Point(3, 0x4b);
            this.ccEncBarYLines.Name = "ccEncBarYLines";
            this.ccEncBarYLines.Size = new Size(0x5f, 30);
            this.ccEncBarYLines.TabIndex = 0;
            this.ccEncBarYLines.Text = "Y-axis lines";
            this.ccEncBarOutlining.AutoSize = true;
            this.ccEncBarOutlining.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccEncBarOutlining.ForeColorSetting = SystemColors.ControlText;
            this.ccEncBarOutlining.Location = new Point(3, 0x6f);
            this.ccEncBarOutlining.Name = "ccEncBarOutlining";
            this.ccEncBarOutlining.Size = new Size(0x61, 30);
            this.ccEncBarOutlining.TabIndex = 0;
            this.ccEncBarOutlining.Text = "Outline pen";
            this.ccEncBarAvgText.AutoSize = true;
            this.ccEncBarAvgText.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccEncBarAvgText.ForeColorSetting = Color.Black;
            this.ccEncBarAvgText.Location = new Point(3, 0x93);
            this.ccEncBarAvgText.Name = "ccEncBarAvgText";
            this.ccEncBarAvgText.Size = new Size(0x88, 30);
            this.ccEncBarAvgText.TabIndex = 0;
            this.ccEncBarAvgText.Text = "Average/Total Text";
            this.ccEncBarColor1.AutoSize = true;
            this.ccEncBarColor1.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccEncBarColor1.ForeColorSetting = Color.DarkRed;
            this.ccEncBarColor1.Location = new Point(3, 0xb7);
            this.ccEncBarColor1.Name = "ccEncBarColor1";
            this.ccEncBarColor1.Size = new Size(0x5e, 30);
            this.ccEncBarColor1.TabIndex = 0;
            this.ccEncBarColor1.Text = "Bar color 1";
            this.ccEncBarColor2.AutoSize = true;
            this.ccEncBarColor2.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccEncBarColor2.ForeColorSetting = Color.DarkBlue;
            this.ccEncBarColor2.Location = new Point(3, 0xdb);
            this.ccEncBarColor2.Name = "ccEncBarColor2";
            this.ccEncBarColor2.Size = new Size(0x5e, 30);
            this.ccEncBarColor2.TabIndex = 0;
            this.ccEncBarColor2.Text = "Bar color 2";
            this.ccEncBarColor3.AutoSize = true;
            this.ccEncBarColor3.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccEncBarColor3.ForeColorSetting = Color.DarkViolet;
            this.ccEncBarColor3.Location = new Point(3, 0xff);
            this.ccEncBarColor3.Name = "ccEncBarColor3";
            this.ccEncBarColor3.Size = new Size(0x5e, 30);
            this.ccEncBarColor3.TabIndex = 0;
            this.ccEncBarColor3.Text = "Bar color 3";
            this.ccEncBarText.AutoSize = true;
            this.ccEncBarText.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccEncBarText.ForeColorSetting = Color.White;
            this.ccEncBarText.Location = new Point(3, 0x123);
            this.ccEncBarText.Name = "ccEncBarText";
            this.ccEncBarText.Size = new Size(0x69, 30);
            this.ccEncBarText.TabIndex = 0;
            this.ccEncBarText.Text = "Bar text color";
            this.groupBox1.Controls.Add(this.btnResetEncBarColors);
            this.groupBox1.Controls.Add(this.flowLayoutPanel1);
            this.groupBox1.Location = new Point(3, 3);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0xf4, 0x159);
            this.groupBox1.TabIndex = 2;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Graph General Colors";
            this.btnResetEncBarColors.Font = new Font("Microsoft Sans Serif", 6.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btnResetEncBarColors.Location = new Point(0xac, -1);
            this.btnResetEncBarColors.Name = "btnResetEncBarColors";
            this.btnResetEncBarColors.Size = new Size(0x45, 0x12);
            this.btnResetEncBarColors.TabIndex = 3;
            this.btnResetEncBarColors.Text = "Reset";
            this.btnResetEncBarColors.UseVisualStyleBackColor = true;
            this.btnResetEncBarColors.Click += new EventHandler(this.btnResetEncBarColors_Click);
            this.groupBox2.Controls.Add(this.btnResetGraphFillColors);
            this.groupBox2.Controls.Add(this.flowLayoutPanel2);
            this.groupBox2.Location = new Point(0xfd, 3);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(0x106, 0x159);
            this.groupBox2.TabIndex = 3;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Graph Fill Colors";
            this.btnResetGraphFillColors.Font = new Font("Microsoft Sans Serif", 6.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btnResetGraphFillColors.Location = new Point(190, -1);
            this.btnResetGraphFillColors.Name = "btnResetGraphFillColors";
            this.btnResetGraphFillColors.Size = new Size(0x45, 0x12);
            this.btnResetGraphFillColors.TabIndex = 3;
            this.btnResetGraphFillColors.Text = "Reset";
            this.btnResetGraphFillColors.UseVisualStyleBackColor = true;
            this.btnResetGraphFillColors.Click += new EventHandler(this.btnResetGraphFillColors_Click);
            this.flowLayoutPanel2.AutoScroll = true;
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill1);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill2);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill3);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill4);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill5);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill6);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill7);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill8);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill9);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill10);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill11);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill12);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill13);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill14);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill15);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill16);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill17);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill18);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill19);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill20);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill21);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill22);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill23);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill24);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill25);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill26);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill27);
            this.flowLayoutPanel2.Controls.Add(this.ccGraphFill28);
            this.flowLayoutPanel2.Dock = DockStyle.Fill;
            this.flowLayoutPanel2.Location = new Point(3, 0x10);
            this.flowLayoutPanel2.Name = "flowLayoutPanel2";
            this.flowLayoutPanel2.Size = new Size(0x100, 0x146);
            this.flowLayoutPanel2.TabIndex = 0;
            this.ccGraphFill1.AutoSize = true;
            this.ccGraphFill1.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill1.ForeColorSetting = Color.FromArgb(0xc0, 0, 0xc0);
            this.ccGraphFill1.Location = new Point(3, 3);
            this.ccGraphFill1.Name = "ccGraphFill1";
            this.ccGraphFill1.Size = new Size(0x66, 30);
            this.ccGraphFill1.TabIndex = 0;
            this.ccGraphFill1.Text = "Graph Fill 01";
            this.ccGraphFill2.AutoSize = true;
            this.ccGraphFill2.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill2.ForeColorSetting = Color.FromArgb(0xff, 0x80, 0xff);
            this.ccGraphFill2.Location = new Point(0x6f, 3);
            this.ccGraphFill2.Name = "ccGraphFill2";
            this.ccGraphFill2.Size = new Size(0x66, 30);
            this.ccGraphFill2.TabIndex = 0;
            this.ccGraphFill2.Text = "Graph Fill 02";
            this.ccGraphFill3.AutoSize = true;
            this.ccGraphFill3.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill3.ForeColorSetting = Color.FromArgb(0, 0, 0xc0);
            this.ccGraphFill3.Location = new Point(3, 0x27);
            this.ccGraphFill3.Name = "ccGraphFill3";
            this.ccGraphFill3.Size = new Size(0x66, 30);
            this.ccGraphFill3.TabIndex = 0;
            this.ccGraphFill3.Text = "Graph Fill 03";
            this.ccGraphFill4.AutoSize = true;
            this.ccGraphFill4.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill4.ForeColorSetting = Color.FromArgb(0x80, 0x80, 0xff);
            this.ccGraphFill4.Location = new Point(0x6f, 0x27);
            this.ccGraphFill4.Name = "ccGraphFill4";
            this.ccGraphFill4.Size = new Size(0x66, 30);
            this.ccGraphFill4.TabIndex = 0;
            this.ccGraphFill4.Text = "Graph Fill 04";
            this.ccGraphFill5.AutoSize = true;
            this.ccGraphFill5.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill5.ForeColorSetting = Color.FromArgb(0, 0xc0, 0xc0);
            this.ccGraphFill5.Location = new Point(3, 0x4b);
            this.ccGraphFill5.Name = "ccGraphFill5";
            this.ccGraphFill5.Size = new Size(0x66, 30);
            this.ccGraphFill5.TabIndex = 0;
            this.ccGraphFill5.Text = "Graph Fill 05";
            this.ccGraphFill6.AutoSize = true;
            this.ccGraphFill6.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill6.ForeColorSetting = Color.FromArgb(0x80, 0xff, 0xff);
            this.ccGraphFill6.Location = new Point(0x6f, 0x4b);
            this.ccGraphFill6.Name = "ccGraphFill6";
            this.ccGraphFill6.Size = new Size(0x66, 30);
            this.ccGraphFill6.TabIndex = 0;
            this.ccGraphFill6.Text = "Graph Fill 06";
            this.ccGraphFill7.AutoSize = true;
            this.ccGraphFill7.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill7.ForeColorSetting = Color.FromArgb(0, 0xc0, 0);
            this.ccGraphFill7.Location = new Point(3, 0x6f);
            this.ccGraphFill7.Name = "ccGraphFill7";
            this.ccGraphFill7.Size = new Size(0x66, 30);
            this.ccGraphFill7.TabIndex = 0;
            this.ccGraphFill7.Text = "Graph Fill 07";
            this.ccGraphFill8.AutoSize = true;
            this.ccGraphFill8.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill8.ForeColorSetting = Color.FromArgb(0x80, 0xff, 0x80);
            this.ccGraphFill8.Location = new Point(0x6f, 0x6f);
            this.ccGraphFill8.Name = "ccGraphFill8";
            this.ccGraphFill8.Size = new Size(0x66, 30);
            this.ccGraphFill8.TabIndex = 0;
            this.ccGraphFill8.Text = "Graph Fill 08";
            this.ccGraphFill9.AutoSize = true;
            this.ccGraphFill9.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill9.ForeColorSetting = Color.FromArgb(0xc0, 0xc0, 0);
            this.ccGraphFill9.Location = new Point(3, 0x93);
            this.ccGraphFill9.Name = "ccGraphFill9";
            this.ccGraphFill9.Size = new Size(0x66, 30);
            this.ccGraphFill9.TabIndex = 0;
            this.ccGraphFill9.Text = "Graph Fill 09";
            this.ccGraphFill10.AutoSize = true;
            this.ccGraphFill10.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill10.ForeColorSetting = Color.FromArgb(0xff, 0xff, 0x80);
            this.ccGraphFill10.Location = new Point(0x6f, 0x93);
            this.ccGraphFill10.Name = "ccGraphFill10";
            this.ccGraphFill10.Size = new Size(0x66, 30);
            this.ccGraphFill10.TabIndex = 0;
            this.ccGraphFill10.Text = "Graph Fill 10";
            this.ccGraphFill11.AutoSize = true;
            this.ccGraphFill11.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill11.ForeColorSetting = Color.FromArgb(0xc0, 0x40, 0);
            this.ccGraphFill11.Location = new Point(3, 0xb7);
            this.ccGraphFill11.Name = "ccGraphFill11";
            this.ccGraphFill11.Size = new Size(0x66, 30);
            this.ccGraphFill11.TabIndex = 0;
            this.ccGraphFill11.Text = "Graph Fill 11";
            this.ccGraphFill12.AutoSize = true;
            this.ccGraphFill12.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill12.ForeColorSetting = Color.FromArgb(0xff, 0xc0, 0x80);
            this.ccGraphFill12.Location = new Point(0x6f, 0xb7);
            this.ccGraphFill12.Name = "ccGraphFill12";
            this.ccGraphFill12.Size = new Size(0x66, 30);
            this.ccGraphFill12.TabIndex = 0;
            this.ccGraphFill12.Text = "Graph Fill 12";
            this.ccGraphFill13.AutoSize = true;
            this.ccGraphFill13.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill13.ForeColorSetting = Color.FromArgb(0xc0, 0, 0);
            this.ccGraphFill13.Location = new Point(3, 0xdb);
            this.ccGraphFill13.Name = "ccGraphFill13";
            this.ccGraphFill13.Size = new Size(0x66, 30);
            this.ccGraphFill13.TabIndex = 0;
            this.ccGraphFill13.Text = "Graph Fill 13";
            this.ccGraphFill14.AutoSize = true;
            this.ccGraphFill14.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill14.ForeColorSetting = Color.FromArgb(0xff, 0x80, 0x80);
            this.ccGraphFill14.Location = new Point(0x6f, 0xdb);
            this.ccGraphFill14.Name = "ccGraphFill14";
            this.ccGraphFill14.Size = new Size(0x66, 30);
            this.ccGraphFill14.TabIndex = 0;
            this.ccGraphFill14.Text = "Graph Fill 14";
            this.ccGraphFill15.AutoSize = true;
            this.ccGraphFill15.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill15.ForeColorSetting = Color.Fuchsia;
            this.ccGraphFill15.Location = new Point(3, 0xff);
            this.ccGraphFill15.Name = "ccGraphFill15";
            this.ccGraphFill15.Size = new Size(0x66, 30);
            this.ccGraphFill15.TabIndex = 0;
            this.ccGraphFill15.Text = "Graph Fill 15";
            this.ccGraphFill16.AutoSize = true;
            this.ccGraphFill16.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill16.ForeColorSetting = Color.FromArgb(0x40, 0, 0x40);
            this.ccGraphFill16.Location = new Point(0x6f, 0xff);
            this.ccGraphFill16.Name = "ccGraphFill16";
            this.ccGraphFill16.Size = new Size(0x66, 30);
            this.ccGraphFill16.TabIndex = 0;
            this.ccGraphFill16.Text = "Graph Fill 16";
            this.ccGraphFill17.AutoSize = true;
            this.ccGraphFill17.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill17.ForeColorSetting = Color.Blue;
            this.ccGraphFill17.Location = new Point(3, 0x123);
            this.ccGraphFill17.Name = "ccGraphFill17";
            this.ccGraphFill17.Size = new Size(0x66, 30);
            this.ccGraphFill17.TabIndex = 0;
            this.ccGraphFill17.Text = "Graph Fill 17";
            this.ccGraphFill18.AutoSize = true;
            this.ccGraphFill18.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill18.ForeColorSetting = Color.FromArgb(0, 0, 0x40);
            this.ccGraphFill18.Location = new Point(0x6f, 0x123);
            this.ccGraphFill18.Name = "ccGraphFill18";
            this.ccGraphFill18.Size = new Size(0x66, 30);
            this.ccGraphFill18.TabIndex = 0;
            this.ccGraphFill18.Text = "Graph Fill 18";
            this.ccGraphFill19.AutoSize = true;
            this.ccGraphFill19.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill19.ForeColorSetting = Color.Aqua;
            this.ccGraphFill19.Location = new Point(3, 0x147);
            this.ccGraphFill19.Name = "ccGraphFill19";
            this.ccGraphFill19.Size = new Size(0x66, 30);
            this.ccGraphFill19.TabIndex = 0;
            this.ccGraphFill19.Text = "Graph Fill 19";
            this.ccGraphFill20.AutoSize = true;
            this.ccGraphFill20.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill20.ForeColorSetting = Color.FromArgb(0, 0x40, 0x40);
            this.ccGraphFill20.Location = new Point(0x6f, 0x147);
            this.ccGraphFill20.Name = "ccGraphFill20";
            this.ccGraphFill20.Size = new Size(0x66, 30);
            this.ccGraphFill20.TabIndex = 0;
            this.ccGraphFill20.Text = "Graph Fill 20";
            this.ccGraphFill21.AutoSize = true;
            this.ccGraphFill21.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill21.ForeColorSetting = Color.Lime;
            this.ccGraphFill21.Location = new Point(3, 0x16b);
            this.ccGraphFill21.Name = "ccGraphFill21";
            this.ccGraphFill21.Size = new Size(0x66, 30);
            this.ccGraphFill21.TabIndex = 0;
            this.ccGraphFill21.Text = "Graph Fill 21";
            this.ccGraphFill22.AutoSize = true;
            this.ccGraphFill22.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill22.ForeColorSetting = Color.FromArgb(0, 0x40, 0);
            this.ccGraphFill22.Location = new Point(0x6f, 0x16b);
            this.ccGraphFill22.Name = "ccGraphFill22";
            this.ccGraphFill22.Size = new Size(0x66, 30);
            this.ccGraphFill22.TabIndex = 0;
            this.ccGraphFill22.Text = "Graph Fill 22";
            this.ccGraphFill23.AutoSize = true;
            this.ccGraphFill23.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill23.ForeColorSetting = Color.Yellow;
            this.ccGraphFill23.Location = new Point(3, 0x18f);
            this.ccGraphFill23.Name = "ccGraphFill23";
            this.ccGraphFill23.Size = new Size(0x66, 30);
            this.ccGraphFill23.TabIndex = 0;
            this.ccGraphFill23.Text = "Graph Fill 23";
            this.ccGraphFill24.AutoSize = true;
            this.ccGraphFill24.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill24.ForeColorSetting = Color.FromArgb(0x40, 0x40, 0);
            this.ccGraphFill24.Location = new Point(0x6f, 0x18f);
            this.ccGraphFill24.Name = "ccGraphFill24";
            this.ccGraphFill24.Size = new Size(0x66, 30);
            this.ccGraphFill24.TabIndex = 0;
            this.ccGraphFill24.Text = "Graph Fill 24";
            this.ccGraphFill25.AutoSize = true;
            this.ccGraphFill25.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill25.ForeColorSetting = Color.FromArgb(0xff, 0x80, 0);
            this.ccGraphFill25.Location = new Point(3, 0x1b3);
            this.ccGraphFill25.Name = "ccGraphFill25";
            this.ccGraphFill25.Size = new Size(0x66, 30);
            this.ccGraphFill25.TabIndex = 0;
            this.ccGraphFill25.Text = "Graph Fill 25";
            this.ccGraphFill26.AutoSize = true;
            this.ccGraphFill26.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill26.ForeColorSetting = Color.FromArgb(0x80, 0x40, 0x40);
            this.ccGraphFill26.Location = new Point(0x6f, 0x1b3);
            this.ccGraphFill26.Name = "ccGraphFill26";
            this.ccGraphFill26.Size = new Size(0x66, 30);
            this.ccGraphFill26.TabIndex = 0;
            this.ccGraphFill26.Text = "Graph Fill 26";
            this.ccGraphFill27.AutoSize = true;
            this.ccGraphFill27.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill27.ForeColorSetting = Color.Red;
            this.ccGraphFill27.Location = new Point(3, 0x1d7);
            this.ccGraphFill27.Name = "ccGraphFill27";
            this.ccGraphFill27.Size = new Size(0x66, 30);
            this.ccGraphFill27.TabIndex = 0;
            this.ccGraphFill27.Text = "Graph Fill 27";
            this.ccGraphFill28.AutoSize = true;
            this.ccGraphFill28.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            this.ccGraphFill28.ForeColorSetting = Color.FromArgb(0x40, 0, 0);
            this.ccGraphFill28.Location = new Point(0x6f, 0x1d7);
            this.ccGraphFill28.Name = "ccGraphFill28";
            this.ccGraphFill28.Size = new Size(0x66, 30);
            this.ccGraphFill28.TabIndex = 0;
            this.ccGraphFill28.Text = "Graph Fill 28";
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.Name = "OpColorGraphing";
            base.Size = new Size(0x20d, 0x167);
            this.flowLayoutPanel1.ResumeLayout(false);
            this.flowLayoutPanel1.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.flowLayoutPanel2.ResumeLayout(false);
            this.flowLayoutPanel2.PerformLayout();
            base.ResumeLayout(false);
        }
    }
}

